/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursionassignment2;

/**
 *
 * @author k00253718
 */
public class RecursionJFrame extends javax.swing.JFrame
{

    /**
     * Creates new form RecursionJFrame
     */
    public RecursionJFrame()
    {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        number1JLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num1JTextField = new javax.swing.JTextField();
        num2JTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputJTextArea = new javax.swing.JTextArea();
        exponentialJRadioButton = new javax.swing.JRadioButton();
        gcdJRadioButton = new javax.swing.JRadioButton();
        factorialJRadioButton = new javax.swing.JRadioButton();
        placeJRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recursion Assignment");
        setName("Recursion Assignment"); // NOI18N

        number1JLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        number1JLabel.setText("Number 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Number 2");

        outputJTextArea.setEditable(false);
        outputJTextArea.setColumns(20);
        outputJTextArea.setRows(5);
        jScrollPane1.setViewportView(outputJTextArea);

        exponentialJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exponentialJRadioButton.setText("Exponential ");
        exponentialJRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exponentialJRadioButtonActionPerformed(evt);
            }
        });

        gcdJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gcdJRadioButton.setText("GCD");
        gcdJRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gcdJRadioButtonActionPerformed(evt);
            }
        });

        factorialJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        factorialJRadioButton.setText("Factorial");
        factorialJRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                factorialJRadioButtonActionPerformed(evt);
            }
        });

        placeJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        placeJRadioButton.setText("Place");
        placeJRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                placeJRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number1JLabel)
                            .addComponent(jLabel2))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exponentialJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gcdJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorialJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placeJRadioButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1JLabel)
                    .addComponent(num1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exponentialJRadioButton)
                    .addComponent(gcdJRadioButton)
                    .addComponent(factorialJRadioButton)
                    .addComponent(placeJRadioButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factorialJRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_factorialJRadioButtonActionPerformed
    {//GEN-HEADEREND:event_factorialJRadioButtonActionPerformed
	int number = Integer.parseInt(num1JTextField.getText());

	outputJTextArea.setText("" + factorialRecursion.factorial(number));
    }//GEN-LAST:event_factorialJRadioButtonActionPerformed

    private void exponentialJRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exponentialJRadioButtonActionPerformed
    {//GEN-HEADEREND:event_exponentialJRadioButtonActionPerformed
	int base = Integer.parseInt(num1JTextField.getText());

	int exponent = Integer.parseInt(num2JTextField.getText());

	outputJTextArea.setText("" + PowerRecursion.power(base, exponent));

    }//GEN-LAST:event_exponentialJRadioButtonActionPerformed

    private void gcdJRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gcdJRadioButtonActionPerformed
    {//GEN-HEADEREND:event_gcdJRadioButtonActionPerformed
	int m = Integer.parseInt(num1JTextField.getText());

	int n = Integer.parseInt(num2JTextField.getText());

	outputJTextArea.setText("" + GCDRecursion.gcd(m, n));
    }//GEN-LAST:event_gcdJRadioButtonActionPerformed

    private void placeJRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_placeJRadioButtonActionPerformed
    {//GEN-HEADEREND:event_placeJRadioButtonActionPerformed
     int number = Integer.parseInt(num1JTextField.getText());
     
     outputJTextArea.setText("" + PlaceRecursion.place(number));
     
    }//GEN-LAST:event_placeJRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Nimbus".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(RecursionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(RecursionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(RecursionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(RecursionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new RecursionJFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton exponentialJRadioButton;
    private javax.swing.JRadioButton factorialJRadioButton;
    private javax.swing.JRadioButton gcdJRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num1JTextField;
    private javax.swing.JTextField num2JTextField;
    private javax.swing.JLabel number1JLabel;
    private javax.swing.JTextArea outputJTextArea;
    private javax.swing.JRadioButton placeJRadioButton;
    // End of variables declaration//GEN-END:variables
}
